/*
*
*		Homework 7
*		Completion Time 2.5 hours
*		@author: Shane McPhillips
*		@version: 1.6
*		@compiler: Visual Studio
*
*/


// CSE240 
// Be sure to add the standard header above.
// Write the compiler used: Visual studio or g++ (SELECT ONE AND INDICATE)


// READ BEFORE YOU START:
// You are given a partially completed program that creates a list of rooms.
// Each room has name, number of rooms and library type (hayden or noble).
// This information is stored as an object of Room class. Class defined in room.h
// The classes Hayden and Noble are child classes of the Room class.
// When adding a new room, these child classes are used to make the room node of the list.
// So each node in the list is actually an object of either Hayden or Noble class.

//
// To begin, you should trace through the given code and understand how it works.
// Please read the instructions above each required function and follow the directions carefully.
// Do not modify given code.

// You can assume that all input is valid:
// Valid name:	String containing alphabetical letters
// Valid number: a positive integer

#include <iostream>
#include <fstream>
#include <string>
#include "Container.h"
#include "room.h"
#include "noble.h"
#include "hayden.h"

using namespace std;

// functions already implemented:
void executeAction(char c);
Room* searchRoom(string name_input);


// functions that need implementation:
void addRoom(string name_input, int no_input, libraryType type);			// 7 points
void displayList();							// 4 points
void save(string fileName);					// 7 points
void load(string fileName);					// 7 points

void changeLibraryType(Room* room, int libType);

Container* list = NULL;				// global list
int numActiveContainers;				// room list size.	

int main()
{
	char c = 'i';				// initialized to a dummy value

  // During first execution, there will be no list.txt in source directory. list.txt is generated by save() while exiting the program.
	load("list.txt");			
	do {
		cout << "\nCSE240 HW7\n";
		cout << "Please enter your selection:\n";
		cout << "\t a: add a new room\n";
		cout << "\t d: display room list\n";
		cout << "\t c: change library type\n";
		cout << "\t q: quit\n";
		cin >> c;
		cin.ignore();
		executeAction(c);
	} while (c != 'q');

	save("list.txt");

	list = NULL;

	return 0;
}

// Ask for details from user for the given selection and perform that action
// Read the function case by case
void executeAction(char c)
{
	string name_input;
	int no_input;
	int type_input = 2;
	libraryType type;
	Room* roomResult = NULL;

	switch (c)
	{
	case 'a':	// add room
				// input room details from user
		cout << endl << "Enter room name: ";
		getline(cin, name_input);
		cout << "Enter number of rooms: ";
		cin >> no_input;
		cin.ignore();

		while (!(type_input == 0 || type_input == 1))
		{
			cout << "Enter library type: " << endl;
			cout << "0. Hayden " << endl;
			cout << "1. Noble" << endl;
			cin >> type_input;
			cin.ignore();
		}
		type = (libraryType)type_input;

		// searchRoom() will return the room object if found, else returns NULL
		roomResult = searchRoom(name_input);
		if (roomResult == NULL)
		{
			addRoom(name_input, no_input, type);
			cout << endl << "Room added to list!" << endl << endl;
		}
		else
			cout << endl << "Room already present in the list!" << endl << endl;

		break;

	case 'd':		// display the list
		displayList();
		break;

	case 'c':		// change room type
		cout << endl << "Enter room name: ";
		getline(cin, name_input);
		// searchRoom() will return the room node if found, else returns NULL
		roomResult = searchRoom(name_input);
		if (roomResult == NULL)
		{
			cout << endl << "Room not in list!" << endl << endl;
		}
		else
		{
			//Ensures choice boundary between [0, 1] inclusive.
			while (!(type_input == 0 || type_input == 1))
			{
				cout << endl << "Enter new library type: " << endl;
					cout << "0. Hayden " << endl;
					cout << "1. Noble" << endl;
				cin >> type_input;
				cin.ignore();
			}
			type = (libraryType)type_input;
			// Q3c Call changeLibraryType() here   (1 point)
			// 'roomResult' contains the room whose Library Type is to be changed.
			// Call the function with appropriate arguments.

			changeLibraryType(roomResult, type_input);

			cout << endl << "Library type changed!" << endl << endl;
		}
		break;

	case 'q':		// quit
		break;

	default: cout << c << " is invalid input!\n";
	}

}

// No implementation needed here, however it may be helpful to review this function
Room* searchRoom(string name_input)
{

	Container* tempList = list;			// work on a copy of 'list'

	while (tempList != NULL)			// parse till end of list
	{
		if (tempList->room->getName() == name_input)
		{
			return tempList->room;	// return the room if found
		}

		tempList = tempList->next;		// parse the list
	}

	return NULL;						// return NULL if room not found in list
}

// Q3b: Define Friend Function changeLibraryType()  (3 points)
// Define the function changeLibraryType()that is declared in room.h file.
// This function sets the new library type for the room. The room object and new library type (as integer) are to be passed as function arguments.
// Use 'd' display option after using 'c' option to verify.
// You will need to implement add() and displayList() before you test this function.
void changeLibraryType(Room* room, int libType) {
	//libType boundary check done in execute func.
	//Change library type using friend class functionality.
	room->lib = (libraryType)libType;
}

// Q4: addRoom  (7 points)
// This function is used to add a new room to the global linked list 'list'. You may add the new room to head or tail of the list. (Sample solution adds to tail)
// libraryType 'type' can be hayden or noble. You will need to use the function argument 'type' to determine which constructor to use to create new room node.
// For example, if the user enters type as 'noble', then you need to use Noble class and constructor to create new room node and add it to the list.
// NOTE: In executeAction(), searchroom() is called before this function. Therefore no need to check here if the room exists in the list.
//       See how this fucntion is called in case 'a' of executeAction()

void addRoom(string name_input, int no_input, libraryType type) 
{
	//Define new container. Lifetime is extended beyond scope.
	Container* newContainer = new Container();
	Room* newRoom;

	//Determine which library type room subclass.
	if (type == hayden) {
		newRoom = new Hayden(name_input, no_input, type);
	}
	else {
		newRoom = new Noble(name_input, no_input, type);
	}

	//set container vars.
	newContainer->room = newRoom;
	newContainer->next = list;

	//Update head.
	list = newContainer;

	//increment room counter.
	numActiveContainers++;
}

// Q5: displayList	(4 points)
// This function displays the list of room and their details (name, no, library name)
// Parse the list and use the class member function to display the room info.
// See expected output in the question file.

void displayList()
{
	Container *tempList = list;			// work on a copy of 'list'
	while (tempList != NULL) {
		tempList->room->displayRoom();
		tempList = tempList->next;
	}
}

// Q6: save  (7 points)
// Save the linked list of rooms to a file list.txt using ofstream.
// You will need to save the number of rooms in linked list. That will help in load() when reading the file.
// One format to store is:
// <no. of rooms>
// <Room1 name>
// <Room1 no>
// <Room type>
// <Room2 name>
// <Room2 no>
// <Room2 type>
// and so on..
// You may store the list in another format if you wish. You need to read the file in load () the same way that it is saved in save().
// This function is called when exiting the program (end of main() ).
// Hint: You may want to cast the enum 'libraryType' to an int before writing it to the file.


void save(string fileName)
{
	//Define a temporary container pointer.
	Container* temp;
	ofstream outFile;

	//Open file. Use trunc flag to open file and clear. This will ensure we clear the file to overwrite. Write in binary.
	outFile.open(fileName, ios::trunc | ios::binary);

	if (!outFile.is_open()) {
		//cout << "Error saving list data to file: " << fileName << endl;
	}
	else {
		//write room count for load processing.
		outFile << numActiveContainers << endl;

		//set temp to head node.
		temp = list;
		while (temp != NULL) {
			outFile << temp->room->getName() << endl;
			outFile << temp->room->getNo() << endl;
			outFile << (int)temp->room->getLibraryType() << endl;
			temp = temp->next;
		}

		//close file
		outFile.close();
	}

	//Garbage Collect.
	//Traverse
	while (list != NULL) {
		//set temp to head node.
		temp = list;
		//head node is now the next node in sequence
		list = list->next;

		//delete operation on head node data.
		delete temp->room;
		temp->room = NULL;
		//delete operation on head node.
		delete temp;
		temp = NULL;
	}
}

// Q7: load (7 points)
// Load the linked list of rooms from the file using ifstream.
// You will need to create the linked list in the same order that is was saved to the file in save().
// First, read the number of rooms saved in the file.
// Then, for every room you will need to create a new Room node depending on room type. You may add the room to head or tail of the list. 
// Hint: If you casted the enum 'libraryType' to an int, you will need to cast it back to 'libraryType' when making the room node.
// This function is called at the beginning of main().

void load(string fileName)
{
	ifstream inFile;
	int containerCount;
	string temp;

	//Open a binary file for reading in.
	inFile.open(fileName, ios::in | ios::binary);

	if (!inFile.is_open()) {
		//cout << "Error loading list data from file: " << fileName << endl;
	}
	else {
		//read in room number = list node number.
		inFile >> containerCount;
		//loop through and retrieve data. Let add functionality above handle room make.
		for (int count = 0; count < containerCount; count++) {
			//Load in room data variables. Name, room count, library-type.
			string roomName;
			int numRooms, libType;
			inFile >> roomName;
			inFile >> numRooms;
			inFile >> libType;

			//Add room using built functionality.
			addRoom(roomName, numRooms, (libraryType)libType);
		}

		//close file.
		inFile.close();
	}
}
